export const RESET_ALL_STATE = 'RESET_ALL_STATE';
export const ROOT_CHANGED = 'ROOT_CHANGED';

// LOGIN ACTION
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_LOGOUT = 'FETCH_LOGOUT';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const REGISTRATION_NOTIFICATION = 'REGISTRATION_NOTIFICATION';

// PERMISSION ACTION
export const CHECK_PERMISSIONS = 'CHECK_PERMISSIONS';
export const REQUEST_PERMISSION_DONE = 'REQUEST_PERMISSION_DONE';

// SIGNUP ACTION
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_ACTIVE_SUCCESS = 'SIGNUP_ACTIVE_SUCCESS';
export const SIGNUP_ACTIVE_FAILED = 'SIGNUP_ACTIVE_FAILED';
export const FETCH_SIGNUP = 'FETCH_SIGNUP';
export const SIGNUP_ACTIVE = 'SIGNUP_ACTIVE';
// ACTION RECOVERY PASSWORD
export const RECOVERY_PASSWORD_SUCCESS = 'RECOVERY_PASSWORD_SUCCESS';
export const RECOVERY_PASSWORD_FAILED = 'RECOVERY_PASSWORD_FAILED';
export const FETCH_RECOVERY_PASSWORD = 'FETCH_RECOVERY_PASSWORD';
// LOADING ACTION
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const CHANGE_STATE_LOADING = 'CHANGE_STATE_LOADING';
export const CHANGE_STATE_LOADING_MYU = 'CHANGE_STATE_LOADING_MYU';

// USER ACTION
export const INITIAL_USER = 'INITIAL_USER';

// BRANCH IO
export const INITIAL_BRANCHIO = 'INITIAL_BRANCHIO';
export const DEEPLINK_SIGNUP_ACTIVE = 'DEEPLINK_SIGNUP_ACTIVE';

// PROFILE ACTION
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_ME = 'GET_ME';
export const UPDATE_PROFILE_DASHBOARD = 'UPDATE_PROFILE_DASHBOARD'

// FOLLOWER 
export const FETCH_FOLLOWER = 'FETCH_FOLLOWER';
export const FOLLOWING = 'FOLLOWING';
export const FETCH_FOLLOWER_SUCCESS = 'FETCH_FOLLOWER_SUCCESS';
export const FETCH_FOLLOWER_ERROR = 'FETCH_FOLLOWER_ERROR';
export const REQUEST_FOLLOWING_ACTION = 'REQUEST_FOLLOWING_ACTION';
export const FOLLOWING_SUCCESS = 'FOLLOWING_SUCCESS';
export const FOLLOWING_ERROR = 'FOLLOWING_ERROR';
export const UNFOLLOWING_SUCCESS = 'UNFOLLOWING_SUCCESS';
export const UNFOLLOWING_ERROR = 'UNFOLLOWING_ERROR';
export const UPDATE_FOLLOWER_LOCAL = 'UPDATE_FOLLOWER_LOCAL';


// BLOCKED/UNBLOCKED USERS
export const REQUEST_BLOCKED_USERS_ACTION = 'REQUEST_BLOCKED_USERS_ACTION';
export const FETCH_BLOCKED_USERS_SUCCESS = 'FETCH_BLOCKED_USERS_SUCCESS';
export const FETCH_BLOCKED_USERS_ERROR = 'FETCH_BLOCKED_USERS_ERROR';
export const BLOCKED_USERS_SUCCESS = 'BLOCKED_USERS_SUCCESS';
export const BLOCKED_USERS_ERROR = 'BLOCKED_USERS_ERROR';
export const UNBLOCKED_USERS_SUCCESS = 'UNBLOCKED_USERS_SUCCESS';
export const UNBLOCKED_USERS_ERROR = 'UNBLOCKED_USERS_ERROR';
export const UPDATE_BLOCKED_USERS_STATUS = 'UPDATE_BLOCKED_USERS_STATUS';
export const FETCH_LIST_BLOCKED_USERS = 'FETCH_LIST_BLOCKED_USERS';
export const FETCH_LIST_BLOCKED_USERS_SUCCESS = 'FETCH_LIST_BLOCKED_USERS_SUCCESS';
export const FETCH_LIST_BLOCKED_USERS_FAILED = 'FETCH_LIST_BLOCKED_USERS_FAILED';
export const FETCH_LIST_BLOCKED_USERS_MORE = 'FETCH_LIST_BLOCKED_USERS_MORE';
export const FETCH_LIST_BLOCKED_USERS_MORE_SUCCESS = 'FETCH_LIST_BLOCKED_USERS_MORE_SUCCESS';
export const REQUEST_LIST_BLOCKED_USERS_ACTION = 'REQUEST_LIST_BLOCKED_USERS_ACTION';
export const UPDATE_UNBLOCK_LOCAL = 'UPDATE_UNBLOCK_LOCAL';


// LIST FOLLOWER/FOLLOWING
export const FETCH_LIST_FOLLOWER = 'FETCH_LIST_FOLLOWER';
export const FETCH_LIST_FOLLOWING = 'FETCH_LIST_FOLLOWING';
export const FETCH_LIST_FOLLOWER_MORE = 'FETCH_LIST_FOLLOWER_MORE';
export const FETCH_LIST_FOLLOWING_MORE = 'FETCH_LIST_FOLLOWING_MORE';
export const FETCH_LIST_FOLLOWER_MORE_SUCCESS = 'FETCH_LIST_FOLLOWER_MORE_SUCCESS';
export const FETCH_LIST_FOLLOWING_MORE_SUCCESS = 'FETCH_LIST_FOLLOWING_MORE_SUCCESS';
export const FETCH_LIST_FOLLOWER_SUCCESS = 'FETCH_LIST_FOLLOWER_SUCCESS';
export const FETCH_LIST_FOLLOWER_ERROR = 'FETCH_LIST_FOLLOWER_ERROR';
export const FETCH_LIST_FOLLOWING_SUCCESS = 'FETCH_LIST_FOLLOWING_SUCCESS';
export const FETCH_LIST_FOLLOWING_ERROR = 'FETCH_LIST_FOLLOWING_ERROR';
export const REQUEST_LIST_FOLLOWER_ACTION = 'REQUEST_LIST_FOLLOWER_ACTION';
export const REQUEST_LIST_FOLLOWING_ACTION = 'REQUEST_LIST_FOLLOWING_ACTION';
export const CLEAR_LIST_FOLLOW = 'CLEAR_LIST_FOLLOW';
export const UPDATE_LIST_FOLLOW_STATUS = 'UPDATE_LIST_FOLLOW_STATUS';


// LIST SEARCH USERS BASIC 
export const FETCH_LIST_SEARCH_USERS_BASIC = 'FETCH_LIST_SEARCH_USERS_BASIC';
export const FETCH_LIST_SEARCH_USERS_BASIC_MORE = 'FETCH_LIST_SEARCH_USERS_BASIC_MORE';
export const FETCH_LIST_SEARCH_USERS_BASIC_SUCCESS = 'FETCH_LIST_SEARCH_USERS_BASIC_SUCCESS';
export const FETCH_LIST_SEARCH_USERS_BASIC_FAILED = 'FETCH_LIST_SEARCH_USERS_BASIC_FAILED';
export const FETCH_LIST_SEARCH_USERS_BASIC_MORE_SUCCESS = 'FETCH_LIST_SEARCH_USERS_BASIC_MORE_SUCCESS';
export const FETCH_LIST_SEARCH_USERS_BASIC_MORE_FAILED = 'FETCH_LIST_SEARCH_USERS_BASIC_MORE_FAILED';
export const REQUEST_LIST_SEARCH_USERS_BASIC_ACTION = 'REQUEST_LIST_SEARCH_USERS_BASIC_ACTION';
export const CLEAR_LIST_SEARCH_USERS = 'CLEAR_LIST_SEARCH_USERS';
export const UPDATE_BUTTON_FOLLOW_LIST_SEARCH_BASIC = 'UPDATE_BUTTON_FOLLOW_LIST_SEARCH_BASIC';
export const UPDATE_BUTTON_FOLLOW_IN_LIST_SEARCH = 'UPDATE_BUTTON_FOLLOW_IN_LIST_SEARCH';


// LIST SEARCH USERS ADVANCED
export const FETCH_LIST_SEARCH_USERS_ADVANCED = 'FETCH_LIST_SEARCH_USERS_ADVANCED';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_MORE = 'FETCH_LIST_SEARCH_USERS_ADVANCED_MORE';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_SUCCESS = 'FETCH_LIST_SEARCH_USERS_ADVANCED_SUCCESS';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_FAILED = 'FETCH_LIST_SEARCH_USERS_ADVANCED_FAILED';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_SUCCESS = 'FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_SUCCESS';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_FAILED = 'FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_FAILED';
export const REQUEST_LIST_SEARCH_USERS_ADVANCED_ACTION = 'REQUEST_LIST_SEARCH_USERS_ADVANCED_ACTION';
export const UPDATE_BUTTON_FOLLOW_LIST_SEARCH_ADVANCED = 'UPDATE_BUTTON_FOLLOW_LIST_SEARCH_ADVANCED';


// LIST SEARCH USERS BASIC _FROM_PROFILE_TAB
export const FETCH_LIST_SEARCH_USERS_BASIC_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_BASIC_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_BASIC_MORE_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_BASIC_MORE_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_BASIC_SUCCESS_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_BASIC_SUCCESS_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_BASIC_FAILED_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_BASIC_FAILED_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_BASIC_MORE_SUCCESS_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_BASIC_MORE_SUCCESS_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_BASIC_MORE_FAILED_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_BASIC_MORE_FAILED_FROM_PROFILE_TAB';
export const REQUEST_LIST_SEARCH_USERS_BASIC_ACTION_FROM_PROFILE_TAB = 'REQUEST_LIST_SEARCH_USERS_BASIC_ACTION_FROM_PROFILE_TAB';
export const CLEAR_LIST_SEARCH_USERS_FROM_PROFILE_TAB = 'CLEAR_LIST_SEARCH_USERS_FROM_PROFILE_TAB';
export const UPDATE_BUTTON_FOLLOW_LIST_SEARCH_BASIC_FROM_PROFILE_TAB = 'UPDATE_BUTTON_FOLLOW_LIST_SEARCH_BASIC_FROM_PROFILE_TAB';
export const UPDATE_BUTTON_FOLLOW_IN_LIST_SEARCH_FROM_PROFILE_TAB = 'UPDATE_BUTTON_FOLLOW_IN_LIST_SEARCH_FROM_PROFILE_TAB';


// LIST SEARCH USERS ADVANCED _FROM_PROFILE_TAB
export const FETCH_LIST_SEARCH_USERS_ADVANCED_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_ADVANCED_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_SUCCESS_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_ADVANCED_SUCCESS_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_FAILED_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_ADVANCED_FAILED_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_SUCCESS_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_SUCCESS_FROM_PROFILE_TAB';
export const FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_FAILED_FROM_PROFILE_TAB = 'FETCH_LIST_SEARCH_USERS_ADVANCED_MORE_FAILED_FROM_PROFILE_TAB';
export const REQUEST_LIST_SEARCH_USERS_ADVANCED_ACTION_FROM_PROFILE_TAB = 'REQUEST_LIST_SEARCH_USERS_ADVANCED_ACTION_FROM_PROFILE_TAB';
export const UPDATE_BUTTON_FOLLOW_LIST_SEARCH_ADVANCED_FROM_PROFILE_TAB = 'UPDATE_BUTTON_FOLLOW_LIST_SEARCH_ADVANCED_FROM_PROFILE_TAB';


//FETCH ENTITIES
export const UPDATE_PULL_REFRESH = 'UPDATE_PULL_REFRESH';
export const FETCH_ENTITIES_SUCCESS = 'FETCH_ENTITIES_SUCCESS';
export const FETCH_ENTITIESMORE_SUCCESS = 'FETCH_ENTITIESMORE_SUCCESS';
export const FETCH_ENTITIES_ERROR = 'FETCH_ENTITIES_ERROR';
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const FETCH_ENTITIESMORE = 'FETCH_ENTITIESMORE';
export const FETCH_ENTITIES_PROFILE_SUCCESS = 'FETCH_ENTITIES_PROFILE_SUCCESS';
export const FETCH_ENTITIES_PROFILE = 'FETCH_ENTITIES_PROFILE';
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const REMOVE_LOCAL_ENTITY = 'REMOVE_LOCAL_ENTITY';


// FETCH ENTITY
export const REQUEST_ENTITY_DETAIL = 'REQUEST_ENTITY_DETAIL';
export const FETCH_ENTITY_SUCCESS = 'FETCH_ENTITY_SUCCESS';
export const FETCH_ENTITY_ERROR = 'FETCH_ENTITY_ERROR';
export const CLEAR_ENTITY_LOCAL = 'CLEAR_ENTITY_LOCAL';


// FETCH COMMENT
export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR';
export const FETCH_COMMENTMORE_SUCCESS = 'FETCH_COMMENTMORE_SUCCESS';
export const FETCH_COMMENTMORE = 'FETCH_COMMENTMORE';
export const FETCH_SUBCOMMENT_MORE_SUCCESS = 'FETCH_SUBCOMMENT_MORE_SUCCESS';
export const FETCH_SUBCOMMENT_MORE = 'FETCH_SUBCOMMENT_MORE';
export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT';
export const REQUEST_EDIT_COMMENT = 'REQUEST_EDIT_COMMENT';
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT';
export const REQUEST_REPLY_COMMENT = 'REQUEST_REPLY_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';
export const UPDATE_FOLLOWING_COMMENT = 'UPDATE_FOLLOWING_COMMENT';
export const FETCH_GREY_COMMENT_DASHBOARD = 'FETCH_GREY_COMMENT_DASHBOARD';

// CHANGE SETTINGS
export const REQUEST_CHANGE_PRIVACY_MODE = 'REQUEST_CHANGE_PRIVACY_MODE';
export const CHANGE_PRIVACY_MODE_SUCCESS = 'CHANGE_PRIVACY_MODE_SUCCESS';
export const CHANGE_PRIVACY_MODE_ERROR = 'CHANGE_PRIVACY_MODE_ERROR';
export const UPDATE_USER_SETTING = 'UPDATE_USER_SETTING';

// FETCH MEDIAS
export const FETCH_MEDIASMORE_SUCCESS = 'FETCH_MEDIASMORE_SUCCESS';
export const FETCH_MEDIAS_SUCCESS = 'FETCH_MEDIAS_SUCCESS';
export const FETCH_MEDIAS_ERROR = 'FETCH_MEDIAS_ERROR';
export const FETCH_MEDIAS = 'FETCH_MEDIAS';
export const FETCH_MEDIASMORE = 'FETCH_MEDIASMORE';
export const FETCH_MEDIASFOLLOWER_SUCCESS = 'FETCH_MEDIASFOLLOWER_SUCCESS';
export const FETCH_MEDIASFOLLOWERMORE_SUCCESS = 'FETCH_MEDIASFOLLOWERMORE_SUCCESS';


// LIKE ENTITY
export const REQUEST_LIKE_ENTITY = 'REQUEST_LIKE_ENTITY';
export const ENTITY_LIKE_SUCCESS = 'ENTITY_LIKE_SUCCESS';
export const ENTITY_LIKE_ERROR = 'ENTITY_LIKE_ERROR';
export const ENTITY_UNLIKE_SUCCESS = 'ENTITY_UNLIKE_SUCCESS';
export const ENTITY_UNLIKE_ERROR = 'ENTITY_UNLIKE_ERROR';

// CREATE POST
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
// SCREEN
export const CHANGE_SCREEN_NAME = 'CHANGE_SCREEN_NAME';

export const UPDATE_IS_UPLOADING = 'UPDATE_IS_UPLOADING';


// DETAIL ENTITY
export const DETAIL_ENTITY = 'DETAIL_ENTITY';

// TOGGLE_MYU
export const TOGGLE_MYU = 'TOGGLE_MYU';
export const BACK_HOME = 'BACK_HOME';

// TOGGLE PRIVACY MODE 
export const TOGGLE_PRIVACY_MODE = 'TOGGLE_PRIVACY_MODE';

// ACTION SORT DASHBOARD
export const SORTDASHBOARD_CHANGE = 'SORTDASHBOARD_CHANGE';
export const SORT_DASHBOARD = 'SORT_DASHBOARD';

//DEVELOP MODE OR PRODUCTION 
export const DEVELOP_FLAG = true;

// CREATE REPORT
export const CREATE_REPORT = 'CREATE REPORT';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAILED = 'CREATE_REPORT_FAILED';

export const CREATE_REPORT_COMMENT = 'CREATE_REPORT_COMMENT';
export const CREATE_REPORT_COMMENT_SUCCESS = 'CREATE_REPORT_COMMENT_SUCCESS';
export const CREATE_REPORT_COMMENT_FAILED = 'CREATE_REPORT_COMMENT_FAILED';

//INVITE FRIENDS
export const INVITE_FRIEND_REQUEST = 'INVITE_FRIEND_REQUEST';
export const INVITE_FRIEND_FAILED = 'INVITE_FRIEND_FAILED';
export const INVITE_FRIEND_SUCCESS = 'INVITE_FRIEND_SUCCESS';
export const INVITE_FRIEND_RESET_STATE = 'INVITE_FRIEND_RESET_STATE';

//NOTIFICATIONS
export const LIST_NOTIFY = 'LIST_NOTIFY';
export const LIST_NOTIFY_SUCCESS = 'LIST_NOTIFY_SUCCESS';
export const LIST_NOTIFY_FAIL = 'LIST_NOTIFY_FAIL';
export const LIST_NOTIFY_LOAD_MORE = 'LIST_NOTIFY_LOAD_MORE';
export const LIST_NOTIFY_LOAD_MORE_SUCCESS = 'LIST_NOTIFY_LOAD_MORE_SUCCESS';
export const LIST_NOTIFY_LOAD_MORE_FAILED = 'LIST_NOTIFY_LOAD_MORE_FAILED';
export const REQUEST_FOLLOW = 'REQUEST_FOLLOW';
export const REQUEST_FOLLOW_SUCCESS = 'REQUEST_FOLLOW_SUCCESS';
export const REQUEST_FOLLOW_FAIL = 'REQUEST_FOLLOW_FAIL';

// check version
export const REQUEST_CHECK_VERSION = 'REQUEST_CHECK_VERSION';
export const CHECK_VERSION = 'CHECK_VERSION';


export const UPDATE_LOADMORE = 'UPDATE_LOADMORE';